<?binding.jca infoMail_db.jca?>
<wsdl:definitions name="infoMail" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AplicacionGeneral/promen/infoMail" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AplicacionGeneral/promen/infoMail" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/infoMail">
    <plt:partnerLinkType name="infoMail_plt">
        <plt:role name="infoMail_role">
            <plt:portType name="tns:infoMail_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/infoMail" schemaLocation="xsd/infoMail_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="infoMailSelect_inputParameters">
        <wsdl:part name="infoMailSelect_inputParameters" element="top:infoMailSelect_paramInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MailsCollection_msg">
        <wsdl:part name="MailsCollection" element="top:MailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="infoMail_ptt">
        <wsdl:operation name="infoMailSelect">
            <wsdl:input message="tns:infoMailSelect_inputParameters"/>
            <wsdl:output message="tns:MailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
